export const customer_data = [
  {
    id: 101,
    date: "10/01/2023",
    branch: "Thane",
    type: "Full",
    amount: 25000,
    bank: "PNB Bank",
    requestBy: "Employee 1",
    employeeCode: "E-1",
    status: "Pending",
  },
  {
    id: 102,
    date: "15/03/2023",
    branch: "Navi Mumbai",
    type: "Full",
    amount: 25000,
    bank: "RBL Bank",
    requestBy: "Employee 2",
    employeeCode: "E-2",
    status: "Approved",
  },
  {
    id: 103,
    date: "10/10/2023",
    branch: "Mumbai",
    type: "Short",
    amount: 225000,
    bank: "PNB Bank",
    requestBy: "Employee 1",
    employeeCode: "E-1",
    status: "Rejected",
  },
  {
    id: 104,
    date: "25/01/2023",
    branch: "Mumbai",
    type: "Short",
    amount: 1555000,
    bank: "SBI Bank",
    requestBy: "Employee 4",
    employeeCode: "E-4",
    status: "Approved",
  },
  {
    id: 105,
    date: "31/10/2023",
    branch: "Vile Parle",
    type: "Short",
    amount: 5000,
    bank: "PNB Bank",
    requestBy: "Employee 3",
    employeeCode: "E-3",
    status: "Rejected",
  },
  {
    id: 106,
    date: "15/06/2023",
    branch: "Andheri",
    type: "Short",
    amount: 25000,
    bank: "RBL Bank",
    requestBy: "Employee 5",
    employeeCode: "E-5",
    status: "Approved",
  },
  {
    id: 107,
    date: "18/07/2023",
    branch: "Kurla",
    type: "Full",
    amount: 250000,
    bank: "PNB Bank",
    requestBy: "Employee 1",
    employeeCode: "E-1",
    status: "Pending",
  },
  {
    id: 108,
    date: "05/11/2023",
    branch: "Lower parel",
    type: "Full",
    amount: 260000,
    bank: "PNB Bank",
    requestBy: "Employee 5",
    employeeCode: "E-5",
    status: "Approved",
  },
];
